export const siteConfig = {
  name: "Makkanchor",
  shortName: "Makkanchor",
  legalName: "Makkanchor Spiritual Creations Private Limited",
  title: "Makkanchor - Premium Laddu Gopal Poshak, Pagdi, Kundan Shringar & Devotional Handicrafts",
  description:
    "Makkanchor is India's premier online store for handcrafted Laddu Gopal Poshak, Designer Pagdis, Kundan Shringar, Bansuri, Jhula, Singhasan, Mandir decor and sacred devotional accessories delivered worldwide.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://makkanchor.com",
  ogImage: "https://makkanchor.com/assets/og-image.jpg",
  keywords: [
    "Makkanchor",
    "Laddu Gopal Poshak",
    "Bal Gopal Dress",
    "Designer Pagdi for Laddu Gopal",
    "Kundan Shringar Set",
    "Laddu Gopal Mukut",
    "Bansuri Flute Laddu Gopal",
    "Handcrafted Jhula Singhasan",
    "Vrindavan Devotional Store",
    "Krishna Shringar Collection",
    "Pooja Essentials",
    "Handmade Spiritual Handicrafts",
    "Janmashtami Special Dresses",
    "Radha Krishna Accessories",
  ],
  email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "support@makkanchor.com",
  phone1: process.env.NEXT_PUBLIC_CONTACT_PHONE_1 || "+91 8013395004",
  phone2: process.env.NEXT_PUBLIC_CONTACT_PHONE_2 || "+91 8013395004",
  whatsapp: "+918013395004",
  address: "College More, Kanchrapara, Kolkata, West Bengal 743145, India",
  contact: {
    email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "support@makkanchor.com",
    phone1: process.env.NEXT_PUBLIC_CONTACT_PHONE_1 || "+91 8013395004",
    phone2: process.env.NEXT_PUBLIC_CONTACT_PHONE_2 || "+91 8013395004",
    whatsapp: "+918013395004",
    address: "College More, Kanchrapara, Kolkata, West Bengal 743145, India",
  },
  currency: "₹",
  currencyCode: "INR",
  socials: {
    instagram: "https://instagram.com/makkanchor",
    facebook: "https://facebook.com/makkanchor",
    youtube: "https://youtube.com/@makkanchor",
    pinterest: "https://pinterest.com/makkanchor",
  },
  logo: {
    src: "/assets/logo.png",
    alt: "Makkanchor - Laddu Gopal Devotional Store",
    width: 160,
    height: 60,
  },
  favicon: "/assets/logo.png",
  categories: [
    { name: "Laddu Gopal Poshak", slug: "poshak", description: "Velvet, Silk, Cotton & Designer Poshaks" },
    { name: "Designer Pagdi & Mukut", slug: "pagdi", description: "Zari, Kundan & Feather Pagdis" },
    { name: "Kundan Shringar & Jewelry", slug: "shringar", description: "Necklace, Haar, Payal, Kundal & Bangles" },
    { name: "Jhula, Singhasan & Bed", slug: "singhasan", description: "Wooden, Brass & Velvet Royal Thrones" },
    { name: "Bansuri & Accessories", slug: "accessories", description: "Silver, Brass, Kundan & Wooden Flutes" },
    { name: "Mandir & Pooja Essentials", slug: "mandir-essentials", description: "Aarti Diyas, Asans, Attar & Shringar Kits" },
  ],
};

export type SiteConfig = typeof siteConfig;
